### PR TITLE
[RFC] Add elf support

### PR DESCRIPTION
**Pull request by schu**
Split the project into two subpackages, bcc and elf:

* bcc holds the go bindings for the bcc framework.

* elf holds new code (from https://github.com/kinvolk/gobpf-elf-loader
  *1* in version 1e0ab5f0c647bdd311d90b117941c64f60a62a70) allowing
  users to load and use precompiled eBPF elf files and thus not require
  bcc plus installed kernel headers.

Next step is to move common code into the bpf package and define
interfaces where feasible.

*1* gobpf-elf-loader itself is based on and extending bpf code from
two projects:

https://github.com/safchain/goebpf by Sylvain Afchain and
https://github.com/cilium/cilium by the Cilium Project

Signed-off-by: Michael Schubert <michael@kinvolk.io>

### CODE REVIEW

**Comment by schu** [comment]
As today is the [IO Visor meeting call])(https://lists.iovisor.org/pipermail/iovisor-dev/2016-December/000562.html), we wanted to open this a RFC.

**Comment by schu** [comment]
Updates:

* Change type names to not include `BPF...` as users should import as bpf:
  ```import bpf "github.com/iovisor/gobpf/elf"```
* Users have to get a PerfMap object per map to poll
* Add `PollStop`
* Cleanup error handling a bit (e.g. remove `fmt.Print...`)

**Comment by schu** [comment]
Unless there are no objections, we would like to merge this soon.

**Comment by 4ast** [comment]
lgtm

**Pull request merged**
