### PR TITLE
add missing args in bpf_prog_load

### PR DESCRIPTION
**Pull request by cpg1111**
Related to: https://github.com/iovisor/gobpf/issues/98

### CODE REVIEW

**Comment by schu** [comment]
Hey, we don't support bcc master but target the latest release (currently v0.4.0), which doesn't have this parameter yet: https://github.com/iovisor/bcc/blob/v0.4.0/src/cc/libbpf.h#L40-L43

**Comment by cpg1111** [comment]
Ah ok. Would this PR still be useful for the future release?

**Comment by dswarbrick** [comment]
bcc 0.5.0 was tagged 21 days ago. Shouldn't this now be merged, in order to support the latest bcc release?

**Comment by schu** [comment]
> bcc 0.5.0 was tagged 21 days ago. Shouldn't this now be merged, in order to support the latest bcc release?

Thanks for the reminder :)

I cherry-picked the `bpf_prog_load` update into https://github.com/iovisor/gobpf/pull/100 (and removed the comment) and will merge later today or tomorrow.

**Pull request closed without merging**
