### PR TITLE
Add doc.go so go mod keeps elf/include folder

### PR DESCRIPTION
**Pull request by tamalsaha**
xref: https://github.com/golang/go/issues/26366#issuecomment-405683150

Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by tamalsaha** [comment]
This is an alternative solution https://github.com/iovisor/gobpf/pull/206

cc: @lebauce

**Comment by bboreham** [comment]
I tried this approach in one of my projects, but it didn't work:

```
$ go get github.com/weaveworks/tcptracer-bpf@eeb9b84
go: finding github.com/weaveworks/tcptracer-bpf eeb9b84
go: downloading github.com/weaveworks/tcptracer-bpf v0.0.0-20200114134159-eeb9b84955bf
go: extracting github.com/weaveworks/tcptracer-bpf v0.0.0-20200114134159-eeb9b84955bf
can't load package: package github.com/weaveworks/tcptracer-bpf: C source files not allowed when not using cgo or SWIG: tcptracer-bpf.c
```

Maybe if you add `import "C"` in `doc.go`?

**Comment by mauriciovasquezbernal** [comment]
@bboreham it works for me on `gobpf`. There are not `.c` files in this folder so I think the problem you mention is not relevant for `gobpf`. Could you please confirm so we can move ahead with this one?

**Comment by bboreham** [comment]
@mauriciovasquezbernal I don't remember all the steps, but it turned out I was confused: the real problem was that the `.c` file is not meant to be compiled (it's eBPF source).
I still prefer #206 based on RSC's statement "the model for go builds is that what's needed to build a package is in that directory, not subdirectories".

**Comment by mauriciovasquezbernal** [comment]
@bboreham Right, I agree. I updated https://github.com/iovisor/gobpf/pull/206 to solve the conflicts. Could you please check if that satisfies your requirements?

**Comment by bboreham** [comment]
It looks right now that #206 still has a merge conflict.

**Comment by lebauce** [comment]
@bboreham I just rebased my PR. Sorry for the delay, completely missed the notifications

**Comment by lebauce** [comment]
@tamalsaha I just pushed a new version of your commit here : https://github.com/lebauce/gobpf/commit/4b4a30bbbc8c0efab2c3eff512e381d287bd1e34
It applies the same trick to new .h and .c folders that were added recenty. Feel free to cherry-pick these changes in your branch. Hopefully we'll be able to merge your branch soon :-)
Thanks

**Comment by tamalsaha** [comment]
@lebauce, Thanks. Feel free to open a new pr and merge that.

**Pull request closed without merging**
